create TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR,
    email   VARCHAR UNIQUE
);

create TABLE IF NOT EXISTS items(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR,
    description  VARCHAR,
    is_available BOOLEAN,
    owner_id     BIGINT REFERENCES users (user_id)
);

create TABLE IF NOT EXISTS bookings(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP,
    end_date   TIMESTAMP,
    item_id    BIGINT REFERENCES items (item_id),
    booker_id  BIGINT REFERENCES users (user_id),
    status     VARCHAR
);

create TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR,
    item_id    BIGINT REFERENCES items (item_id),
    author_id  BIGINT REFERENCES users (user_id)
);

