drop table IF EXISTS users CASCADE;
drop table IF EXISTS requests CASCADE;
drop table IF EXISTS items CASCADE;
drop table IF EXISTS bookings CASCADE;
drop table IF EXISTS comments CASCADE;

create TABLE IF NOT EXISTS users(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR,
    email   VARCHAR UNIQUE
    CONSTRAINT user_const CHECK (name <> '' AND email <> '' ),
    CONSTRAINT exist_user_email UNIQUE (email),
    CONSTRAINT exist_user_name UNIQUE (name)
);

create TABLE IF NOT EXISTS requests(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR,
    requestor_id BIGINT REFERENCES users (user_id)
);

create TABLE IF NOT EXISTS items(
    item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR,
    description  VARCHAR,
    is_available BOOLEAN,
    owner_id     BIGINT REFERENCES users (user_id),
    request_id   BIGINT REFERENCES requests (request_id)
);

create TABLE IF NOT EXISTS bookings(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP,
    end_date   TIMESTAMP,
    item_id    BIGINT REFERENCES items (item_id),
    booker_id  BIGINT REFERENCES users (user_id),
    status     VARCHAR
);

create TABLE IF NOT EXISTS comments(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR,
    item_id    BIGINT REFERENCES items (item_id),
    author_id  BIGINT REFERENCES users (user_id)
);

